# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcbabushka_pb2 as grpcbabushka__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/grpcbabushka.Greeter/Get',
                request_serializer=grpcbabushka__pb2.GetRequest.SerializeToString,
                response_deserializer=grpcbabushka__pb2.GetReply.FromString,
                )
        self.Set = channel.unary_unary(
                '/grpcbabushka.Greeter/Set',
                request_serializer=grpcbabushka__pb2.SetRequest.SerializeToString,
                response_deserializer=grpcbabushka__pb2.SetReply.FromString,
                )
        self.ConnectServer = channel.unary_unary(
                '/grpcbabushka.Greeter/ConnectServer',
                request_serializer=grpcbabushka__pb2.ConnectRequest.SerializeToString,
                response_deserializer=grpcbabushka__pb2.ConnectReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=grpcbabushka__pb2.GetRequest.FromString,
                    response_serializer=grpcbabushka__pb2.GetReply.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=grpcbabushka__pb2.SetRequest.FromString,
                    response_serializer=grpcbabushka__pb2.SetReply.SerializeToString,
            ),
            'ConnectServer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectServer,
                    request_deserializer=grpcbabushka__pb2.ConnectRequest.FromString,
                    response_serializer=grpcbabushka__pb2.ConnectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcbabushka.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcbabushka.Greeter/Get',
            grpcbabushka__pb2.GetRequest.SerializeToString,
            grpcbabushka__pb2.GetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcbabushka.Greeter/Set',
            grpcbabushka__pb2.SetRequest.SerializeToString,
            grpcbabushka__pb2.SetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcbabushka.Greeter/ConnectServer',
            grpcbabushka__pb2.ConnectRequest.SerializeToString,
            grpcbabushka__pb2.ConnectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
