# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PATH/babushkaproto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PATH/babushkaproto.proto\x12\rbabushkaproto\"f\n\x0c\x43ommandReply\x12\x14\n\x0c\x63\x61llback_idx\x18\x01 \x01(\r\x12\x15\n\x08response\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_responseB\x08\n\x06_error\"B\n\x07Request\x12\x14\n\x0c\x63\x61llback_idx\x18\x01 \x01(\r\x12\x14\n\x0crequest_type\x18\x02 \x01(\r\x12\x0b\n\x03\x61rg\x18\x03 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PATH.babushkaproto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDREPLY._serialized_start=43
  _COMMANDREPLY._serialized_end=145
  _REQUEST._serialized_start=147
  _REQUEST._serialized_end=213
# @@protoc_insertion_point(module_scope)
